import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ul>
          <li><Link href="/site-1/two-components">Site 1 - two components</Link></li>
          <li><Link href="/site-2/two-components">Site 2 - two components</Link></li>
          <li><Link href="/site-1/serverHtml">Site 1 - useServerInsertedHTML</Link></li>
          <li><Link href="/site-2/serverHtml">Site 2 - useServerInsertedHTML</Link></li>
          <li><Link href="/site-1/dynamic">Site 1 - next/dynamic</Link></li>
          <li><Link href="/site-2/dynamic">Site 2 - next/dynamic</Link></li>
        </ul>
        {children}
      </body>
    </html>
  );
}
